import { ArrowDownRight, ArrowUpRight, CalendarDays, CheckCircle2, Clock3, IndianRupee, UsersRound } from "lucide-react";
import { CollectionChart } from "@/features/dashboard/components/collection-chart";

const metrics = [
  ["Total Members", "248", "+12 this month", UsersRound, "bg-violet-100 text-violet-600"],
  ["Monthly Collection", "₹ 48,650", "+8.2% from July", IndianRupee, "bg-fuchsia-100 text-fuchsia-600"],
  ["Pending Payments", "32", "Needs follow-up", Clock3, "bg-rose-100 text-rose-700"],
  ["Total Expense", "216", "87% collection rate", CheckCircle2, "bg-emerald-100 text-emerald-700"],
] as const;

const payments = [["Rahul Patil", "AUG 2026", "₹500", "Approved"], ["Priya Sharma", "AUG 2026", "₹500", "Pending"], ["Amit Desai", "AUG 2026", "₹1,000", "Approved"], ["Sneha Joshi", "AUG 2026", "₹500", "Pending"]];

export function DashboardContent() {
  return <section className="mx-auto max-w-7xl p-5 md:p-9">
    <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold tracking-tight">Dashboard</h2><p className="mt-1 text-sm text-stone-500">Here&apos;s what&apos;s happening with SSYM today.</p></div><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-[#7257f4] to-[#a858ef] px-4 py-2.5 text-sm font-semibold text-white shadow-lg shadow-violet-200 hover:brightness-105"><CalendarDays size={17} /> August 2026</button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, trend, Icon, tone], index) => <article key={label} className="rounded-2xl border border-white bg-white/90 p-5 shadow-[0_12px_30px_rgb(77_55_135_/_0.07)]"><div className="flex items-start justify-between"><span className={`rounded-2xl p-3 ${tone}`}><Icon size={21} /></span><span className={`flex items-center text-xs font-semibold ${index === 2 ? "text-rose-600" : "text-emerald-600"}`}>{index === 2 ? <ArrowDownRight size={15} /> : <ArrowUpRight size={15} />}</span></div><p className="mt-5 text-sm font-medium text-stone-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p><p className="mt-2 text-xs text-stone-400">{trend}</p></article>)}</div>
    <div className="mt-6 grid gap-6 xl:grid-cols-3"><article className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm xl:col-span-2"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold">Monthly Collection</h3><p className="text-sm text-stone-500">Payment collection over the last 6 months</p></div><span className="rounded-lg bg-amber-50 px-3 py-1.5 text-xs font-semibold text-[#a95f08]">This year</span></div><CollectionChart /></article><article className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><h3 className="font-bold">Collection Progress</h3><p className="text-sm text-stone-500">August 2026 target</p><div className="mt-8 flex justify-center"><div className="flex size-40 flex-col items-center justify-center rounded-full border-[14px] border-[#f0b950] border-l-[#f9e4b5]"><strong className="text-3xl">87%</strong><span className="text-xs text-stone-500">₹48,650 raised</span></div></div><div className="mt-7 space-y-3 text-sm"><div className="flex justify-between"><span className="text-stone-500">Target</span><strong>₹56,000</strong></div><div className="flex justify-between"><span className="text-stone-500">Remaining</span><strong>₹7,350</strong></div></div></article></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-5"><article className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm xl:col-span-3"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-bold">Recent Payments</h3><p className="text-sm text-stone-500">Latest member payment activity</p></div><a className="text-sm font-semibold text-[#a95f08]" href="#">View all</a></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-y border-stone-100 text-xs uppercase tracking-wide text-stone-400"><tr><th className="py-3 font-medium">Member</th><th className="py-3 font-medium">Month</th><th className="py-3 font-medium">Amount</th><th className="py-3 font-medium">Status</th></tr></thead><tbody>{payments.map(([name, month, amount, status]) => <tr key={name} className="border-b border-stone-100"><td className="py-3 font-semibold">{name}</td><td className="py-3 text-stone-500">{month}</td><td className="py-3 font-semibold">{amount}</td><td className="py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${status === "Approved" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{status}</span></td></tr>)}</tbody></table></div></article><article className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm xl:col-span-2"><div className="flex items-center justify-between"><div><h3 className="font-bold">Upcoming Events</h3><p className="text-sm text-stone-500">Don&apos;t miss these moments</p></div><a href="#" className="text-sm font-semibold text-[#a95f08]">View all</a></div><div className="mt-5 space-y-4"><div className="flex gap-3"><span className="rounded-xl bg-amber-50 px-3 py-2 text-center text-xs font-bold text-[#a95f08]">15<br /><span className="font-medium">AUG</span></span><div><p className="font-semibold">Independence Day Celebration</p><p className="text-sm text-stone-500">9:00 AM · SSYM Hall</p></div></div><div className="flex gap-3"><span className="rounded-xl bg-orange-50 px-3 py-2 text-center text-xs font-bold text-orange-700">24<br /><span className="font-medium">AUG</span></span><div><p className="font-semibold">Monthly Member Meeting</p><p className="text-sm text-stone-500">6:30 PM · Community Hall</p></div></div></div></article></div>
  </section>;
}
