import { redirect } from "next/navigation";
import type { ReactNode } from "react";
import { CalendarDays, Mail, Pencil, Phone, ShieldCheck, UserRound } from "lucide-react";
import { auth } from "@/auth";
import { DashboardShell } from "@/features/dashboard/components/dashboard-shell";

export default async function ProfilePage() {
  const session = await auth();
  if (!session?.user.isActive) redirect("/login");
  const user = session.user;
  return <DashboardShell section="Account" title="My Profile"><main className="mx-auto max-w-5xl p-5 md:p-9"><div className="mb-7"><h2 className="text-2xl font-bold tracking-tight">My Profile</h2><p className="mt-1 text-sm text-stone-500">Manage your personal details and account information.</p></div><section className="overflow-hidden rounded-2xl border border-white bg-white shadow-[0_12px_30px_rgb(77_55_135_/_0.07)]"><div className="h-28 bg-gradient-to-r from-[#654dde] via-[#8657ef] to-[#bd5ce8]" /><div className="relative px-6 pb-7"><div className="-mt-12 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div className="flex items-end gap-4"><span className="flex size-24 items-center justify-center rounded-2xl border-4 border-white bg-gradient-to-br from-[#7257f4] to-[#bf5eea] text-3xl font-bold text-white shadow-lg">SA</span><div className="pb-1"><h3 className="text-xl font-bold">{user.name ?? "Super Admin"}</h3><p className="text-sm text-stone-500">Super Administrator</p></div></div><button className="inline-flex items-center justify-center gap-2 rounded-xl border border-[#e6e1f3] px-4 py-2.5 text-sm font-semibold text-[#7257f4] hover:bg-violet-50"><Pencil size={16} /> Edit Profile</button></div><div className="mt-8 grid gap-4 border-t border-stone-100 pt-6 sm:grid-cols-2"><Info icon={<Mail size={18} />} label="Email address" value={user.email ?? "admin@ssym.local"} /><Info icon={<Phone size={18} />} label="Phone number" value="Not added" /><Info icon={<ShieldCheck size={18} />} label="Role" value="Super Admin" /><Info icon={<CalendarDays size={18} />} label="Member since" value="August 2026" /></div></div></section><section className="mt-6 rounded-2xl border border-white bg-white p-6 shadow-[0_12px_30px_rgb(77_55_135_/_0.07)]"><div className="flex items-center gap-3"><span className="rounded-xl bg-violet-100 p-3 text-[#7257f4]"><UserRound size={20} /></span><div><h3 className="font-bold">Account security</h3><p className="text-sm text-stone-500">Keep your account protected with a secure password.</p></div></div><button className="mt-5 rounded-xl bg-violet-50 px-4 py-2.5 text-sm font-semibold text-[#7257f4] hover:bg-violet-100">Change password</button></section></main></DashboardShell>;
}

function Info({ icon, label, value }: { icon: ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-xl bg-[#faf9ff] p-4"><span className="text-[#7657f6]">{icon}</span><div><p className="text-xs font-medium text-stone-500">{label}</p><p className="mt-0.5 text-sm font-semibold">{value}</p></div></div>; }
